
service: aws-serverless-typescript
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}  

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get

custom:	
  esbuild:	
    bundle: true	
    minify: true

plugins:
  - serverless-esbuild
  #- serverless-plugin-typescript
  - serverless-offline
  